import type { Event } from './types';

export const events: Event[] = [
  {
    id: '1',
    title: 'InnovateX Tech Conference',
    description: 'A full day of talks and workshops on the future of technology, from AI to blockchain.',
    date: '2024-10-26',
    time: '09:00 AM',
    location: 'Engineering Hall Auditorium',
    category: 'Conference',
    organizer: 'Tech Club',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'technology conference',
  },
  {
    id: '2',
    title: 'Startup Pitch Night',
    description: 'Watch the brightest minds on campus pitch their business ideas to a panel of venture capitalists.',
    date: '2024-11-05',
    time: '06:00 PM',
    location: 'Business School, Room 301',
    category: 'Competition',
    organizer: 'Entrepreneurship Society',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'startup pitch',
  },
  {
    id: '3',
    title: 'Fall Semester Concert',
    description: 'An outdoor concert featuring local bands and student performers. Free food and drinks!',
    date: '2024-09-22',
    time: '04:00 PM',
    location: 'University Lawn',
    category: 'Music',
    organizer: 'Student Government',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'music concert',
  },
  {
    id: '4',
    title: 'Art & Design Exhibition',
    description: 'Explore stunning work from students of the Fine Arts department, from paintings to sculptures.',
    date: '2024-11-15',
    time: '12:00 PM',
    location: 'Grand Art Gallery',
    category: 'Exhibition',
    organizer: 'Art Department',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'art exhibition',
  },
  {
    id: '5',
    title: 'Career Fair 2024',
    description: 'Meet recruiters from top companies in tech, finance, and marketing. Bring your resume!',
    date: '2024-10-10',
    time: '10:00 AM',
    location: 'Grand Gymnasium',
    category: 'Career',
    organizer: 'Career Services',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'career fair',
  },
  {
    id: '6',
    title: 'Hackathon for Social Good',
    description: 'A 24-hour coding marathon to build solutions for real-world social problems.',
    date: '2024-11-30',
    time: '05:00 PM',
    location: 'Computer Science Building',
    category: 'Hackathon',
    organizer: 'Coders for a Cause',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'coding hackathon',
  },
];

export const organizerEvents = events.filter(e => ['Tech Club', 'Entrepreneurship Society', 'Coders for a Cause'].includes(e.organizer));
