import type { Event } from './types';

export const events: Event[] = [
  {
    id: '1',
    title: 'InnovateX Tech Conference',
    description: 'A full day of talks and workshops on the future of technology, from AI to blockchain.',
    date: '2024-10-26',
    time: '09:00 AM',
    location: 'Engineering Hall Auditorium',
    category: 'Conference',
    organizer: 'Tech Club',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'technology conference',
    instagramPostUrl: 'https://instagram.com/p/1',
  },
  {
    id: '2',
    title: 'Startup Pitch Night',
    description: 'Watch the brightest minds on campus pitch their business ideas to a panel of venture capitalists.',
    date: '2024-11-05',
    time: '06:00 PM',
    location: 'Business School, Room 301',
    category: 'Competition',
    organizer: 'Entrepreneurship Society',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'startup pitch',
    instagramPostUrl: '',
  },
  {
    id: '3',
    title: 'Fall Semester Concert',
    description: 'An outdoor concert featuring local bands and student performers. Free food and drinks!',
    date: '2024-09-22',
    time: '04:00 PM',
    location: 'University Lawn',
    category: 'Music',
    organizer: 'Student Government',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'music concert',
    instagramPostUrl: 'https://instagram.com/p/3',
  },
  {
    id: '4',
    title: 'Art & Design Exhibition',
    description: 'Explore stunning work from students of the Fine Arts department, from paintings to sculptures.',
    date: '2024-11-15',
    time: '12:00 PM',
    location: 'Grand Art Gallery',
    category: 'Exhibition',
    organizer: 'Art Department',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'art exhibition',
    instagramPostUrl: '',
  },
  {
    id: '5',
    title: 'Career Fair 2024',
    description: 'Meet recruiters from top companies in tech, finance, and marketing. Bring your resume!',
    date: '2024-10-10',
    time: '10:00 AM',
    location: 'Grand Gymnasium',
    category: 'Career',
    organizer: 'Career Services',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'career fair',
    instagramPostUrl: 'https://instagram.com/p/5',
  },
  {
    id: '6',
    title: 'Hackathon for Social Good',
    description: 'A 24-hour coding marathon to build solutions for real-world social problems.',
    date: '2024-11-30',
    time: '05:00 PM',
    location: 'Computer Science Building',
    category: 'Hackathon',
    organizer: 'Coders for a Cause',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'coding hackathon',
    instagramPostUrl: '',
  },
   {
    id: '7',
    title: 'Intro to Web Dev Workshop',
    description: 'A hands-on workshop covering the basics of HTML, CSS, and JavaScript.',
    date: '2024-09-28',
    time: '01:00 PM',
    location: 'Library, Room 2B',
    category: 'Workshop',
    organizer: 'Tech Club',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'coding workshop',
    instagramPostUrl: '',
  },
  {
    id: '8',
    title: 'Welcome Week Mixer',
    description: 'An old event that is more than 2 months in the past to demonstrate filtering.',
    date: '2024-07-01',
    time: '05:00 PM',
    location: 'Campus Green',
    category: 'Social',
    organizer: 'Student Union',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'social party',
    instagramPostUrl: '',
  },
  {
    id: '9',
    title: 'Winter Gala',
    description: 'A formal event to celebrate the end of the semester. Dress to impress!',
    date: '2024-12-14',
    time: '07:00 PM',
    location: 'Grand Ballroom',
    category: 'Social',
    organizer: 'Student Union',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'formal gala',
    instagramPostUrl: 'https://instagram.com/p/9',
  },
  {
    id: '10',
    title: 'AI Ethics Debate',
    description: 'A spirited debate on the ethical implications of artificial intelligence. Open to all students.',
    date: '2025-01-20',
    time: '03:00 PM',
    location: 'Philosophy Hall, Room 101',
    category: 'Conference',
    organizer: 'Philosophy Club',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'ai ethics',
    instagramPostUrl: '',
  },
  {
    id: '11',
    title: 'Live Jazz Night',
    description: 'Relax and enjoy an evening of live jazz music performed by the university jazz ensemble.',
    date: '2025-02-05',
    time: '08:00 PM',
    location: 'Student Lounge',
    category: 'Music',
    organizer: 'Music Department',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'jazz music',
    instagramPostUrl: 'https://instagram.com/p/11',
  },
  {
    id: '12',
    title: 'Photography Walk',
    description: 'Join the photography club for a scenic walk around campus to capture the beauty of autumn.',
    date: '2024-10-19',
    time: '02:00 PM',
    location: 'Meet at the Main Gate',
    category: 'Workshop',
    organizer: 'Photography Club',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'photography nature',
    instagramPostUrl: 'https://instagram.com/p/12',
  },
  {
    id: '13',
    title: 'Poetry Slam Night',
    description: 'An open mic night for poets and spoken word artists. Share your work or come to listen.',
    date: '2024-11-08',
    time: '07:30 PM',
    location: 'Campus Coffee House',
    category: 'Music',
    organizer: 'Literature Society',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'poetry stage',
    instagramPostUrl: '',
  },
  {
    id: '14',
    title: 'Mid-Term Study Marathon',
    description: 'A quiet and focused study session with free coffee and snacks to help you prep for mid-terms.',
    date: '2024-10-22',
    time: '10:00 AM',
    location: 'Library, 3rd Floor',
    category: 'Academic',
    organizer: 'Student Success Center',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'library books',
    instagramPostUrl: '',
  }
];

export const organizerEvents = events.filter(e => ['Tech Club', 'Entrepreneurship Society', 'Coders for a Cause'].includes(e.organizer));
